# -*- coding: utf-8 -*-
"""Aula1_Introducao_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQ2jXoCrA54QXRELuW824HCrMG62rIco
"""

print("Olá Mundo")

print("Estou aprendendo Python")

"Estou aprendendo Python"

1 + 1

10 - 2

#Multiplicação
2 * 2

#Divisão
10/5

a = 8
b = 7

a + b

#Criando uma variável do tipo string
frase = "Python para análise de dados"

frase[0]

frase[0:10]

frase[10:]

frase[:19]

frase.count(" ")

frase.lower()

frase = frase.upper()

frase.replace("Python","Frases")

frase

