# -*- coding: utf-8 -*-
"""Aula3_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vC6sSTqN7tojX8mi82c1RhzVAEdgPWnU

# **Análise de dados(Pandas)** - *Ivan Grand Champs*
"""

from google.colab import drive
drive.mount('/content/drive')

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/datasets/Gapminder.csv",error_bad_lines=False, sep=";")

#Visualizando as 5 primeiras linhas
df.head()

df = df.rename(columns={"country":"Pais", "continent": "continente", "year":"Ano", "lifeExp":"Expectativa de vida", "pop":"Pop Total", "gdpPercap": "PIB"})

df.head(15)

#Total de linhas e colunas
df.shape

df.columns

df.dtypes

df.tail(25)

df.describe()

df["continente"].unique()

Oceania = df.loc[df["continente"] == "Oceania"]
Oceania.head(10)

Oceania["continente"].unique()

df.groupby("continente")["Pais"].nunique()

df.groupby("Ano")["Expectativa de vida"].mean()

df["PIB"].mean()

df["PIB"].sum()

